import{S as L,i as g}from"./assets/vendor-7659544d.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const u=document.querySelector(".gallery"),m=document.querySelector(".search-form"),c=document.querySelector(".loader"),f="gallery-link";let d=1;const l=document.getElementById("load-more");l.addEventListener("click",function(){c.style.display="block",y(m.elements.query.value,d).then(function({hits:o}){if(Array.isArray(o)&&o.length>0){const r=o.map(h).join("");u.innerHTML+=r,d++}else i("No more images to load."),l.style.display="none"}).catch(function(o){i(`Error fetching images: ${o}`)}).finally(function(){c.style.display="none"})});m.addEventListener("submit",function(o){o.preventDefault();const r=o.target.elements.query.value;r!==""&&(u.innerHTML="",c.style.display="block",y(r).then(function({hits:s,total:n}){if(Array.isArray(s)&&s.length>0){const e=s.map(h).join("");u.innerHTML=e,F(`Was found: ${n} images`),new L(`.${f}`).refresh(),l.style.display="block"}else i("Sorry, there are no images matching your search query. Please try again!"),l.style.display="none"}).catch(function(s){i(`Error fetching images: ${s}`)}).finally(function(){m.reset(),c.style.display="none"}))});const p={titleColor:"#FFFFFF",messageColor:"#FFFFFF",messageSize:"16px",position:"topRight",displayMode:"replace",closeOnEscape:!0,pauseOnHover:!1,maxWidth:432,messageSize:"16px",messageLineHeight:"24px"};function i(o){g.show({message:o,backgroundColor:"#EF4040",progressBarColor:"#FFE0AC",icon:"icon-close",...p})}function F(o){g.show({message:o,backgroundColor:"#59A10D",progressBarColor:"#B5EA7C",icon:"icon-chek",...p})}const v="https://pixabay.com/api/";function y(o,r){const n=`?${new URLSearchParams({key:"42317586-b983a1ee46e38e925d954d84d",q:o,image_type:"photo",orientation:"horizontal",safeSearch:!0,per_page:6,page:r})}`,e=v+n;return fetch(e).then(t=>t.json()).catch(t=>{throw i(`Error fetching images: ${t}`),t})}function h({largeImageURL:o,tags:r,webformatURL:s,likes:n,views:e,comments:t,downloads:a}){return`
  <a href="${o}" class="${f}">
     <figure>
      <img src="${s}" alt="${r}" class="gallery-image">
      <figcaption class="gallery__figcaption">
        <div class="image-item">Likes <span class="image-elem">${n}</span></div>
        <div class="image-item">Views <span class="image-elem">${e}</span></div>
        <div class="image-item">Comments <span class="image-elem">${t}</span></div>
        <div class="image-item">Downloads <span class="image-elem">${a}</span></div>
      </figcaption>
     </figure>
  </a>
`}
//# sourceMappingURL=commonHelpers.js.map
